DROP DATABASE IF EXISTS university;
CREATE DATABASE university; 
USE university;

CREATE TABLE groups (
id INT(11) NOT NULL AUTO_INCREMENT,
number VARCHAR(50) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY number (number)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE student (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
date DATE NOT NULL,
group_id INT(11) NOT NULL,
PRIMARY KEY (id),
KEY name (name),
kEY date (date),
FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;
